-- Create table for asset manufacturers (makes) used by ITAM assets
create table if not exists public.itam_makes (
  id integer generated by default as identity primary key,
  tenant_id bigint not null references public.tenants (id),
  organisation_id uuid references public.organisations (id),
  name text not null,
  code text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable Row Level Security
alter table public.itam_makes enable row level security;

-- Allow users to view makes in their organisation or tenant
create policy org_isolation_select_itam_makes
on public.itam_makes
for select
using (
  (organisation_id = get_user_org())
  or (organisation_id is null and tenant_id = (
    select profiles.tenant_id from profiles where profiles.id = auth.uid()
  ))
);

-- Allow admins/owners/editors to manage makes within their org or tenant
create policy org_isolation_manage_itam_makes
on public.itam_makes
for all
using (
  (
    (organisation_id = get_user_org())
    or (organisation_id is null and tenant_id = (
      select profiles.tenant_id from profiles where profiles.id = auth.uid()
    ))
  )
  and exists (
    select 1 from users
    where users.auth_user_id = auth.uid()
      and users.role = any (array['admin','owner','editor'])
  )
)
with check (
  (organisation_id = get_user_org())
  or (organisation_id is null and tenant_id = (
    select profiles.tenant_id from profiles where profiles.id = auth.uid()
  ))
);
